version: "2"
services:
  openwebrx:
    image: jketterl/openwebrx-full
    container_name: openwebrx
    ports:
    - "8073:8073/tcp"
    volumes:
    - "./config/config_webrx.py:/opt/openwebrx/config_webrx.py:ro"
    - "./config/bookmarks.json:/opt/openwebrx/bookmarks.json:ro"
    - "./config/htdocs/include/header.include.html:/opt/openwebrx/htdocs/include/header.include.html:ro"
    - "./config/rotator.json:/opt/openwebrx/htdocs/rotator.json:ro"
    - "./config/test.html:/opt/openwebrx/htdocs/test.html:ro"
    - "./config/htdocs/hamlib.js:/opt/openwebrx/htdocs/hamlib.js:ro"
    - "./config/htdocs/index.html:/opt/openwebrx/htdocs/index.html:ro"
    devices:
    - "/dev/bus/usb:/dev/bus/usb"
    tmpfs:
    - /tmp/openwebrx
    restart: unless-stopped
# docker run --device /dev/bus/usb -p 8073:8073 -v openwebrx-config:/etc/openwebrx jketterl/openwebrx
    logging:
        options:
            max-size: 5m
